export const FETCH_LESSONS_REQUEST = 'FETCH_LESSONS_REQUEST';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_LESSONS_FAILED = 'FETCH_LESSONS_FAILED';

export const FETCH_LESSON_BY_ID_REQUEST = 'FETCH_LESSON_BY_ID_REQUEST';
export const FETCH_LESSON_BY_ID_SUCCESS = 'FETCH_LESSON_BY_ID_SUCCESS';
export const FETCH_LESSON_BY_ID_FAILED = 'FETCH_LESSON_BY_ID_FAILED';